### ISSUE TITLE
Cannot invoke "javax.servlet.http.HttpServletRequest.getAttribute(String)" because "this.mPollRequest" is null

### ISSUE THREAD

**Issue by Artur-** [socketio/engine.io-server-java#46]
I am trying out socket.io to see if it fits our needs and ran into this issue when calling `send` from multiple threads on the server with long polling enabled. Based on #19 it seems like `send` should be thread safe but I still occasionally get
```
    java.lang.NullPointerException: Cannot invoke "javax.servlet.http.HttpServletRequest.getAttribute(String)" because "this.mPollRequest" is null
            at io.socket.engineio.server.transport.Polling.send(Polling.java:118)
            at io.socket.engineio.server.EngineIoSocket.flush(EngineIoSocket.java:422)
            at io.socket.engineio.server.EngineIoSocket.sendPacket(EngineIoSocket.java:413)
            at io.socket.engineio.server.EngineIoSocket.send(EngineIoSocket.java:114)
            at io.socket.socketio.server.SocketIoClient.lambda$sendPacket$0(SocketIoClient.java:74)
            at io.socket.socketio.server.parser.IOParser$Encoder.encode(IOParser.java:39)
            at io.socket.socketio.server.SocketIoClient.sendPacket(SocketIoClient.java:68)
            at io.socket.socketio.server.SocketIoSocket.sendPacket(SocketIoSocket.java:382)
            at io.socket.socketio.server.SocketIoSocket.send(SocketIoSocket.java:218)
            at io.socket.socketio.server.SocketIoSocket.send(SocketIoSocket.java:195)
            at dev.hilla.push.SocketIoServlet.send(SocketIoServlet.java:147)
```
with `io.socket:socket.io-server:jar:4.0.0`

**Comment by trinopoty** [comment]
Can you confirm if you have async support enabled or not on your servlet handler.

**Comment by Artur-** [comment]
Async is enabled

**Comment by Artur-** [comment]
Looking at the code I don't see how it could work, maybe I am reading it wrong.

`send` assumes `mPollRequest` is not null
After sending data, `mPollRequest` is set to null
When the client reconnects, `mPollRequest` is set to non-null

So if `send` is called when the client is not connected, it will always fail?

**Comment by trinopoty** [comment]
The POST request is supposed to come in while the GET is blocked on long polling.

**Comment by trinopoty** [comment]
I've published a new version 6.1.0 that has a fix for this bug. Please try it out and let me know if it fixes your issue.
It should be available on maven within a few hours.

You can override the current version by explicitly specifying the new engine.io version in your pom.xml or build.gradle

**Comment by Artur-** [comment]
Nice! I can no longer reproduce this problem with 6.1.0

**Comment by Artur-** [comment]
This seems to still happen from time to time only less frequently. This is with `io.socket:engine.io-server:jar:6.1.0:compile` when running a couple of integration tests in parallel.

```
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "javax.servlet.http.HttpServletRequest.getAttribute(String)" because "this.mPollRequest" is null] with root cause
java.lang.NullPointerException: Cannot invoke "javax.servlet.http.HttpServletRequest.getAttribute(String)" because "this.mPollRequest" is null
	at io.socket.engineio.server.transport.Polling.send(Polling.java:118)
	at io.socket.engineio.server.EngineIoSocket.onRequest(EngineIoSocket.java:218)
	at io.socket.engineio.server.EngineIoServer.handleRequest(EngineIoServer.java:172)
	at dev.hilla.push.EngineIoHandler.httpHandler(EngineIoHandler.java:66)
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
```

**Comment by benjamin-bader** [comment]
I'm seeing this same behavior using socket.io server 4.1.0, transitively depending on engine.io-server-java 6.3.2.

Because I'm using socket.io for a debug server for mobile devs, I can do a gross hack here - I added a critical section around `EngineIoServer.handleRequest`, and the errors stopped.  Just a data point.  Incidentally, I think probably our mobile app has a bug and is opening two sessions concurrently.
